c**********************************************************************
c*                  PARAMETER                                         *
c*                                                                    *
c* nrp= max number of receivers
c* ncp= max number of layers
c**********************************************************************

      implicit real*8 (a-b,d-h,o-z)
      implicit complex*16 (c)
      integer nrp,ncp,in,out
      parameter (nrp=7000,ncp=15,in=10,out=11)
